name: Build and test
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run every hour. This helps detect flakiness,
    # and broken external dependencies.
    - cron: "0 * * * *"

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros: foxy
            ubuntu: focal
          - ros: galactic
            ubuntu: focal
          - ros: humble
            ubuntu: jammy
          - ros: rolling
            ubuntu: jammy

    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu }}-latest

    name: ROS 2 ${{ matrix.ros }}
    steps:
      - run: |
          echo "repositories: {}" > /tmp/deps.repos
      - run: |
          cat > /tmp/deps.repos <<EOF
          repositories:
            rosbag2:
              type: git
              url: https://github.com/ros2/rosbag2
              version: rolling
          EOF
        if: ${{ matrix.ros == 'rolling' }}
      - name: Build and test
        id: action-ros-ci
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: rosbag2_storage_mcap
          target-ros2-distro: ${{ matrix.ros }}
          vcs-repo-file-url: /tmp/deps.repos
      - uses: actions/upload-artifact@v1
        with:
          name: colcon-logs
          path: ros_ws/log
